sonar.host.url=http://13.53.198.230:9000
sonar.projectKey=secret-notes-frontend
sonar.projectName=Secret Notes Frontend
sonar.login=squ_925f831e72246c421795a0326f80a2daae8e38b4

sonar.sources=src
sonar.exclusions=src/**/*.test.js, node_modules/**

sonar.tests=src
sonar.test.inclusions=src/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info